<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/07/29 16:21:44
sfConfig::add(array(
  'app_version' => '0.4.1',
  'app_currency_decimals' => array (
  'BHD' => 3,
  'IQD' => 3,
  'JOD' => 3,
  'KWD' => 3,
  'LYD' => 3,
  'OMR' => 3,
  'TND' => 3,
  'BIF' => 0,
  'BYR' => 0,
  'CLP' => 0,
  'DJF' => 0,
  'HUF' => 0,
  'ISK' => 0,
  'JPY' => 0,
  'KMF' => 0,
  'KRW' => 0,
  'MGA' => 0,
  'PYG' => 0,
  'RWF' => 0,
  'VUV' => 0,
  'XPF' => 0,
),
  'app_dashboard_max_results' => 5,
  'app_pagination_max_results' => 10,
  'app_notification_timeout' => 10000,
  'app_sfDateTimePlugin_format_database' => '%Y-%m-%d %H:%M:%S',
  'app_sf_guard_plugin_remember_cookie_name' => 'SiwappRememberMe',
  'app_sf_guard_plugin_success_signin_url' => '@dashboard',
  'app_sf_guard_plugin_success_signout_url' => '@dashboard',
  'app_sf_guard_plugin_password_min_length' => 4,
  'app_semantics' => array (
  'forbidden' => 
  array (
    'modules' => 
    array (
      0 => 'sfguardauth',
    ),
    'actions' => 
    array (
      0 => 'index',
    ),
  ),
),
  'app_modules_mandatory' => array (
  'dashboard' => 
  array (
    'tab_name' => 'Dashboard',
    'new_button_name' => 'New Invoice',
  ),
  'invoices' => 
  array (
    'tab_name' => 'Invoices',
    'new_button_name' => 'New Invoice',
  ),
  'recurring' => 
  array (
    'tab_name' => 'Recurring Invoices',
    'new_button_name' => 'New Recurring Invoice',
  ),
),
  'app_modules_optional' => array (
  'customers' => 
  array (
    'verbose_name' => 'Customers Module',
    'tab_name' => 'Customers',
    'new_button_name' => 'New Customer',
  ),
  'estimates' => 
  array (
    'verbose_name' => 'Estimates Module',
    'tab_name' => 'Estimates',
    'new_button_name' => 'New Estimate',
  ),
  'products' => 
  array (
    'verbose_name' => 'Products Module',
    'tab_name' => 'Products',
    'new_button_name' => 'New Product',
  ),
),
));
