<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/07/29 16:21:45

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=siwapp',
  'username' => 'ruthi',
  'password' => 'ruthi',
  'name' => 'doctrine',
)),);
