<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/07/29 16:22:09
sfConfig::add(array(
  'mod_search_enabled' => true,
  'mod_search_view_class' => 'sfPHP',
  'mod_search_urls_variables' => array (
  'toggleTagCloud' => 'search/toggleTagCloud',
  'findCustomers' => 'search/ajaxCustomerAutocomplete',
),
));
