<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/07/29 17:07:09
sfConfig::add(array(
  'mod_payments_enabled' => true,
  'mod_payments_view_class' => 'sfPHP',
  'mod_payments_urls_variables' => array (
  'addPayment' => 'payments/add',
  'paymentsForm' => 'payments/form',
  'refreshPayments' => 'payments/refresh',
),
));
