<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/07/29 16:56:46
sfConfig::add(array(
  'mod_estimates_enabled' => true,
  'mod_estimates_view_class' => 'sfPHP',
  'mod_estimates_urls_variables' => array (
  'editRow' => 'estimates/edit',
  'calculateInvoice' => 'common/calculate',
  'printHtml' => '@estimates_print?action=print',
  'printPdf' => '@estimates_print?action=pdf',
),
));
