<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/07/29 16:21:46
sfConfig::add(array(
  'mod_dashboard_enabled' => true,
  'mod_dashboard_view_class' => 'sfPHP',
  'mod_dashboard_urls_include' => array (
  0 => 'payments',
  1 => 'search',
),
  'mod_dashboard_urls_variables' => array (
  'editRow' => 'invoices/edit',
  'getTotalDue' => 'dashboard/getTotalDue',
),
));
