<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/07/29 16:57:07
sfConfig::add(array(
  'mod_customers_enabled' => true,
  'mod_customers_view_class' => 'sfPHP',
  'mod_customers_urls_include' => array (
  0 => 'search',
),
  'mod_customers_urls_variables' => array (
  'editRow' => 'customers/edit',
  'showInvoices' => 'customers/showInvoices',
),
));
