<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/07/29 16:21:46
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'passwordrecovery' => 
  array (
    'is_secure' => false,
  ),
  'passwordreset' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
