<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/07/29 16:14:42

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=siwapp',
  'username' => 'siwapp',
  'password' => 'wappis',
  'name' => 'doctrine',
)),);
